"""Added pending_amount to Member

Revision ID: 7472232b6c34
Revises: 2fbb461776ce
Create Date: 2024-02-13 22:52:16.809261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7472232b6c34'
down_revision = '2fbb461776ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('pending_amount')

    # ### end Alembic commands ###
